version: '3'

services:

  server:
    build: ./racedata-manager
    links:
      - db
    ports:
      - 5000:5000
    environment:
      - APP_ENV=dev

  db:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_DATABASE: 'tantrix5_CompBase'
        MYSQL_ROOT_PASSWORD: 'Daliluni5'
    ports:
    - 32000:3306

  client:
    build: ./racedata-client
    environment:
      - APP_ENV=dev
      - APP_BACKEND_URL=server:5000
      - APP_FRONTEND_PORT=40002
    ports:
      - 3000:3000
    